Repository lieser/dkim_verifier, pull requests merged in 2023-06, with the labels that each got.

#370 Update UK translation
  _locales/uk/messages.json
Labels: localization

#371 Update zh_TW translation
  _locales/zh_TW/messages.json
Labels: localization

#372 Develop/5.3.0 ja jp
  _locales/ja_JP/messages.json
Labels: localization

#373 Update Italian translations
  _locales/it/messages.json
Labels: localization

#375 Backport Feature 5 -> 2.x JSDNS improvements and offline mode support
  chrome/locale/de/dkim.properties
  chrome/locale/en-US/dkim.properties
  chrome/locale/fr/dkim.properties
  chrome/locale/hu/dkim.properties
  chrome/locale/it/dkim.properties
  chrome/locale/ja-JP/dkim.properties
  chrome/locale/zh-CN/dkim.properties
  modules/DNSWrapper.jsm
  modules/libunbound.jsm
  thirdparty/dns/JSDNS.jsm
Labels: enhancement

#376 Support for adding favicon by auid or from address
  modules/AuthVerifier.jsm
  modules/dkimPolicy.jsm
Labels: enhancement

#377 Added favicon for Posteo support
  data/favicon.json
  data/favicon/posteo.de.png
Labels: default sign rules/favicon
