Repository lieser/dkim_verifier, pull requests merged in 2025-05, with the labels that each got.

#514 Translate two strings to vi_VN
  _locales/vi_VN/messages.json
Labels: localization

#517 Updated favicons and sign rules from master 2025-05-19
  data/favicon.json
  data/favicon/boulderwelt.de.png
  data/favicon/decathlon.de.svg
  data/favicon/lampenwelt.de.svg
  data/signersDefault.json
Labels: default sign rules/favicon

#523 Backport: 6x -> 2x: Display option for DMARC and SPF
  chrome/content/dkim.js
  chrome/content/options_display.xul
  chrome/locale/de/options.dtd
  chrome/locale/en-US/options.dtd
  chrome/locale/fr/options.dtd
  chrome/locale/hu/options.dtd
  chrome/locale/it/options.dtd
  chrome/locale/ja-JP/options.dtd
  chrome/locale/zh-CN/options.dtd
  defaults/preferences/prefs.js
  modules/helper.jsm.js
Labels: enhancement
