Repository lieser/dkim_verifier, pull requests merged in 2025-01, with the labels that each got.

#471 Multiglob_support
  manifest.json
  modules/dkim/signRules.mjs.js
  test/unittest/signRulesSpec.mjs.js
Labels: enhancement

#475 2.x: Prefer ed25519 over rsa signatures
  modules/dkimVerifier.jsm.js
Labels: enhancement

#469 2.x: Added option to try to sanitize a modified subject if verification fails
  chrome/content/options_advanced.xul
  chrome/locale/de/dkim.properties
  chrome/locale/de/options.dtd
  chrome/locale/en-US/dkim.properties
  chrome/locale/en-US/options.dtd
  chrome/locale/fr/dkim.properties
  chrome/locale/fr/options.dtd
  chrome/locale/hu/dkim.properties
  chrome/locale/hu/options.dtd
  chrome/locale/it/dkim.properties
  chrome/locale/it/options.dtd
  chrome/locale/ja-JP/dkim.properties
  chrome/locale/ja-JP/options.dtd
  chrome/locale/zh-CN/dkim.properties
  chrome/locale/zh-CN/options.dtd
  defaults/preferences/prefs.js
  modules/dkimVerifier.jsm.js
Labels: enhancement

#476 2.x: Fix a display issue with Silvermel theme
  chrome/skin/global/msgHdrViewOverlay.css
Labels: compatibility

#478 2.x: Backport: Trim whitespace to ensure date parsing will work
  modules/dkimVerifier.jsm.js
Labels: bug

#479 2.x: Backport: Allow up to 3 levels of nested comments in ARH
  modules/rfcParser.jsm.js
Labels: bug

#481 Update zh_TW translation
  _locales/zh_TW/messages.json
Labels: localization

#482 Update Brazilian Portuguese translation
  _locales/pt_BR/messages.json
Labels: localization

#483 Update messages.json with pl translation
  _locales/pl/messages.json
Labels: localization

#484 #480 - Update FR translation for v5.5.0
  _locales/fr/messages.json
Labels: localization

#449 2.x: Backport feature detailed results 5 to 2x
  chrome/content/dkim.js
  chrome/content/options_display.js
  chrome/content/options_display.xul
  chrome/locale/de/dkim.properties
  chrome/locale/de/options.dtd
  chrome/locale/en-US/dkim.properties
  chrome/locale/en-US/options.dtd
  chrome/locale/fr/dkim.properties
  chrome/locale/fr/options.dtd
  chrome/locale/hu/dkim.properties
  chrome/locale/hu/options.dtd
  chrome/locale/it/dkim.properties
  chrome/locale/it/options.dtd
  chrome/locale/ja-JP/dkim.properties
  chrome/locale/ja-JP/options.dtd
  chrome/locale/zh-CN/dkim.properties
  chrome/locale/zh-CN/options.dtd
  defaults/preferences/prefs.js
  modules/AuthVerifier.d.ts
  modules/AuthVerifier.jsm.js
  modules/dkimVerifier.jsm.js
Labels: enhancement

#485 Add "vi_VN" locale
  _locales/vi_VN/description.txt
  _locales/vi_VN/developerComments.txt
  _locales/vi_VN/messages.json
  _locales/vi_VN/privacyPolicy.txt
Labels: localization

#487 Ukrainian Localization update for 5.5.0 #480
  _locales/uk/messages.json
Labels: localization

#488 Update ja_JP translation for v5.5.0 (#480)
  _locales/ja_JP/messages.json
Labels: localization

#489 Backported favicons.json from master at 12.01.2025
  data/favicon.json
Labels: default sign rules/favicon
